### ISSUE TITLE
Add flag for state machine status

### ISSUE THREAD

**Issue by rgcoe** [PMEC-OSU/FOSTWIN#15]
From today's information session: Can you add a flag that the controller can see to indicate the state machine state?

**Comment by johannes-spinneken** [comment]
@ryancoe @bretbosma @Graham-EGI 

I implemented the changes required to bring the supervisor state back to the absorption controller sub-system. I have implemented and tested these locally, but not committed them back to GitHub yet.

The changes are simple (see details below). However, these changes also mean that the code will not be "backwards" compatible, as we are changing the number of inputs to the absorption controller model from 2 to 3.

I do feel that the change is sufficiently important, and we can work with participants to communicate this change. Without knowing the supervisor state, the absorption controller cannot reset any internal state (e.g. an integrator term). This is not just relevant during a fault/instability, but also during startup when the supervisor state machine is in an "init" state for a few seconds.

Any views?

---

Details of changes.

Bring state back from state machine into absorption controller block. This requires a unit delay block to avoid an algebraic loop.

![image](https://user-images.githubusercontent.com/49918117/217381671-9c229ba7-50bd-4533-aa94-41567a2e41e2.png)

The state can now be used in the absorption controller sub-system, to for example reset an integrator. A reset is not required in the default controller model (which has no internal state), but may be required by more complex controllers.

![image](https://user-images.githubusercontent.com/49918117/217381888-d45570ce-5e47-4c9a-8e23-2e753305382f.png)

**Comment by rgcoe** [comment]
Yes, let's go ahead and merge the changes. Hopefully anyone with a potential problem will see this Issue and/or find it later.

**Comment by johannes-spinneken** [comment]
We made a minor modification to the code, which now allows users to reset their internal controller state based on the supervisor state.
 
The change is shown at the bottom of the image below. The controller model now has a third input, which is the supervisor state. The updated code is [available on GitHub](https://github.com/PMEC-OSU/FOSTWIN), and the code is now also updated in our [Speedgoat real-time environment](https://fostwin.evergreeninnovations.co/).
 
For users planning to use the [Speedgoat real-time environment](https://fostwin.evergreeninnovations.co/), please update your controller code with the additional input. The controller code will not compile otherwise. Usage of the additional input is optional (can be terminated as shown below), but the input must be present and of type int32 as [updated here](https://github.com/PMEC-OSU/FOSTWIN/blob/main/defaultCtrlModel.slx).

For users wishing to use the supervisor state for any type of controller reset, the definition of the various [supervisor states can be found here.](https://github.com/PMEC-OSU/FOSTWIN/blob/bf94735aa920c1abb485359f2f911a9cc95251f5/initModels_GUI.m#L180-L187)

![image](https://user-images.githubusercontent.com/49918117/218601036-3c78d215-5a21-416e-aa6e-8aa39f1d4d52.png)
